telegram-bot:
  botName: my_peesduke_bot
  token: 6914704304:AAHq-uqGYPma84FU9IOXRhGkzoyBGhL2XyI

spring:
  jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url:                       jdbc:postgresql://localhost:5432/telegram_bot?verifyCertificate=true&useSSL=true
    username:                  telegram_bot
    password:                  telegram_bot